{
 "title": "[PROD] Minecraft Network",
 "description": "Featuring Proxy, SMP and Limbo",
 "tags": [
  "Minecraft",
  "Production"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": {
     "query": "label_values(voidlink_proxy_managed_servers,proxy_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_entities)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(voidlink_proxy_jvm_memory{proxy_name=~\".*\"}) by (proxy_name))"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voidlink_proxy_managed_servers{proxy_name=~\"$proxy\"}",
     "legendFormat": "{{proxy_name}}"
    }
   ]
  },
  {
   "title": "Plugins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voidlink_proxy_installed_network_plugins{proxy_name=~\"$proxy\"}",
     "legendFormat": "{{proxy_name}}"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voidlink_proxy_online_player{proxy_name=~\"$proxy\"})",
     "legendFormat": "Online Player"
    }
   ]
  },
  {
   "title": "Online Player List",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "voidlink_proxy_online_player > 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "$proxy RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(voidlink_proxy_jvm_memory{type='allocated', proxy_name=~\"$proxy\"}) - scalar(sum(voidlink_proxy_jvm_memory{type='free', proxy_name=~\"$proxy\"}))"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_max(avg(voidlink_proxy_online_player_latency > 0),1000)",
     "legendFormat": "average player ping"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\",area=\"heap\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (server) (voidlink_proxy_online_player{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Players in {{world}}"
    }
   ]
  },
  {
   "title": "Events per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voidlink_proxy_player_chats_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "chats"
    },
    {
     "expr": "increase(voidlink_proxy_server_list_pings_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "server list pings"
    },
    {
     "expr": "increase(voidlink_proxy_player_connects_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "connects"
    },
    {
     "expr": "increase(voidlink_proxy_player_kicks_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "kicks"
    },
    {
     "expr": "increase(voidlink_proxy_player_disconnects_total{proxy_name=~\"$proxy\"}[1m])",
     "legendFormat": "disconnects"
    }
   ]
  },
  {
   "title": "Loaded chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Loaded chunks in {{world}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (voidlink_proxy_jvm_memory{type='used',proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} used"
    },
    {
     "expr": "sum by (type) (voidlink_proxy_jvm_memory{type='free',proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} free"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(voidlink_proxy_jvm_threads_current{proxy_name=~\"$proxy\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum by (state) (voidlink_proxy_jvm_threads_state{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Top entities by type",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}